# This is a basic workflow to help you get started with Actions
name: Auto merge and deploy files by schedules

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [trigger-tttt-from-cronjob]
    
  workflow_dispatch: # Allows you to run the action manually for testing
  
permissions:
  contents: write # Required to push changes back to the repo
  pages: write # Required to deploy github pages
  id-token: write # Required to deploy github pages

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: github
  cancel-in-progress: true
  
jobs:
  merge-commit-and-deploy:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Start the job
      - name: Start the job
        run: |
          echo Hello, world! 

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: 'thtt27/thtt'
          token: ${{ secrets.PAT_THTT }}
          
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm aiohttp lxml pysocks selenium-wire
      - name: Show current time
        run: |
          cp  python/* .
          echo "Current datetime: $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          if [ -f helloworld.py ]; then
            python helloworld.py
          fi
          git pull
          
      - name: Download file via curl
        run: |
          # curl -s -k -H "Authorization: token ${{ secrets.PAT_THTT }}" -L -o ${{ secrets.NAME_THETHAO }} ${{ secrets.URL_PRIVATE_FILES_REPO }}/${{ secrets.NAME_THETHAO }}  & 
          # curl -s -k -H "Authorization: token ${{ secrets.PAT_THTT }}" -L -o xoilacztv.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/xoilacztv.py  & 
          # curl -s -k -H "Authorization: token ${{ secrets.PAT_THTT }}" -L -o apisports.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/apisports.py & 
          # curl -s -k -H "Authorization: token ${{ secrets.PAT_THTT }}" -L -o gavangtv.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/gavangtv.py & 
          # curl -s -k -H "Authorization: token ${{ secrets.PAT_THTT }}" -L -o testproxies.py ${{ secrets.URL_PRIVATE_FILES_REPO }}/python/testproxies.py & 
          # curl -s -k -H "Authorization: token ${{ secrets.PAT_THTT }}" -L -o keys.json ${{ secrets.URL_PRIVATE_FILES_REPO }}/jsonfiles/keys.json & 
          
          wait
          ls -lh

      - name: Download, get & convert links to M3U files
        run: |
          # if [ -f testproxies.py ]; then
          #   python testproxies.py etc/proxies.txt &
          # fi
        
          if [ -f xoilacztv.py ]; then
            python xoilacztv.py https://xoilacz.io xoilacztv.m3u  & 
          fi

          if [ -f gavangtv.py ]; then
            python gavangtv.py https://gavanglink.org gavangtv.m3u &
          fi
          
          if [ -f apisports.py ]; then
            python apisports.py sutbong sutbongtv.m3u &
            python apisports.py khandai khandaitv.m3u &
            python apisports.py phalang phalangtv.m3u &

            python apisports.py chuoichien chuoichientv.m3u &
            python apisports.py saoke saoketv.m3u &
            python apisports.py gavang33 gavang33tv.m3u &
            python apisports.py giovang giovangtv.m3u &
            python apisports.py cola colatv.m3u &
            python apisports.py vuasanco vuasancotv.m3u &
            python apisports.py biaom biaomtv.m3u &
            python apisports.py s8tv s8tv.m3u &
          fi
          
          wait
      
      # Runs a set of commands using the runners shell
      - name: Merge Files
        # Combine base.m3u, tt.m3u and other m3u files into full.m3u
        run: |
          # delete old full.m3u, tt.m3u before merge
          rm -f ${{ secrets.NAME_THTHETHAO }}
          rm -f ${{ secrets.NAME_TTTHETHAO }}
          mkdir -p src
          # ls -lh

          echo "#EXTM3U" >> lastupdated.m3u
          echo "#EXTINF:-1 group-title='Updated' , $(date -u +'%Y-%m-%dT%H:%MZ')" >> lastupdated.m3u
          echo "https://freem3u.xyz/static/no-signal/low.m3u8" >> lastupdated.m3u
          echo " " >> lastupdated.m3u
          cat lastupdated.m3u >> ${{ secrets.NAME_TTTHETHAO }}
          echo " " >> lastupdated.m3u
          
          if [ -f vuasancotv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat vuasancotv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi
          if [ -f khandaitv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat khandaitv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi
          if [ -f chuoichientv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat chuoichientv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi
          if [ -f giovangtv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat giovangtv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi
          if [ -f biaomtv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat biaomtv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi
          if [ -f s8tv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat s8tv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi
          if [ -f saoketv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat saoketv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi
          if [ -f xoilacztv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat xoilacztv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi         
          if [ -f gavang33tv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat gavang33tv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi
          if [ -f colatv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat colatv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi
          if [ -f sutbongtv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat sutbongtv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi
          if [ -f gavangtv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat gavangtv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi
          if [ -f phalangtv.m3u ]; then
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
            cat phalangtv.m3u >> ${{ secrets.NAME_TTTHETHAO }}
            echo " " >> ${{ secrets.NAME_TTTHETHAO }}
          fi

          if [ -f ${{ secrets.NAME_THETHAO }} ]; then
            cat ${{ secrets.NAME_THETHAO }} > ${{ secrets.NAME_THTHETHAO }}
          fi 
          echo " " >> ${{ secrets.NAME_THTHETHAO }}
          if [ -f ${{ secrets.NAME_TTTHETHAO }} ]; then
            cat ${{ secrets.NAME_TTTHETHAO }} >> ${{ secrets.NAME_THTHETHAO }}
          fi
          echo " " >> ${{ secrets.NAME_THTHETHAO }}
          
          ls -lh

          echo "Last updated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > lastupdated.txt

          [ -f ${{ secrets.NAME_THTHETHAO }} ] && cp ${{ secrets.NAME_THTHETHAO }} src/
          # [ -f ${{ secrets.NAME_THETHAO }} ] && cp ${{ secrets.NAME_THETHAO }} src/
          [ -f ${{ secrets.NAME_TTTHETHAO }} ] && cp ${{ secrets.NAME_TTTHETHAO }} src/

          [ -f keys.json ] && cp keys.json src/
          
          # ls -lh src/

          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          retention-days: 0
          # Upload in src/ folder only
          path: 'src/'

      - name: Retry Deployment on Failure
        id: deployment
        uses: Wandalen/wretry.action@v3
        with:
          action: actions/deploy-pages@v5  # Swap this out for your specific deployment action
          attempt_limit: 3
          attempt_delay: 3
    
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v5        

      - name: Delete artifact validation file
        uses: geekyeggo/delete-artifact@v6
        with:
          name: |
              github-pages.zip
              github-pages
          failOnError: false
      
      - name: Commit and push changes
        run: |
          git config --local user.name "thtt [bot]"
          git add lastupdated.txt
          git add src/*
          # git add etc/testing/host.txt

          echo "checking any changes"
          if git diff --staged --quiet; then
            echo "[test only] No changes detected."
          fi
          
          git pull
          git commit --allow-empty -m "[no ci] Update repo" && git push
